Repository NeuraLegion/sectester-net, pull requests merged in 2022-12, with the labels that each got.

#75 feat(repeater): implement a repeater
  src/SecTester.Core/Utils/SystemTimerProvider.cs
  src/SecTester.Core/Utils/TimerProvider.cs
  src/SecTester.Repeater/Bus/RegisterRepeaterCommand.cs
  src/SecTester.Repeater/Bus/RegisterRepeaterResult.cs
  src/SecTester.Repeater/Bus/RepeaterRegisteringError.cs
  src/SecTester.Repeater/Bus/RepeaterStatusEvent.cs
  src/SecTester.Repeater/Extensions/SemaphoreSlimExtensions.cs
  src/SecTester.Repeater/Internal/AutoReleasableSemaphore.cs
  src/SecTester.Repeater/Repeater.cs
  src/SecTester.Repeater/RunningStatus.cs
  test/SecTester.Repeater.Tests/Api/DefaultRepeatersTests.cs
  test/SecTester.Repeater.Tests/Extensions/SemaphoreSlimExtensionsTests.cs
  test/SecTester.Repeater.Tests/Mocks/MockLogger.cs
  test/SecTester.Repeater.Tests/RepeaterTests.cs
  test/SecTester.Repeater.Tests/SecTester.Repeater.Tests.csproj
Labels: Type: enhancement

#82 refactor(core): extract a common `SemaphoreSlimExtensions`
  src/SecTester.Core/Extensions/SemaphoreSlimExtensions.cs
  src/SecTester.Core/Internal/AutoReleasableSemaphore.cs
  src/SecTester.Repeater/Repeater.cs
  test/SecTester.Core.Tests/Extensions/SemaphoreSlimExtensionsTests.cs
Labels: Type: refactoring

#80 feat(repeater): implement an EventBus factory
  src/SecTester.Bus/Dispatchers/DefaultRmqEventBusFactory.cs
  src/SecTester.Bus/Dispatchers/RmqEventBus.cs
  src/SecTester.Bus/Dispatchers/RmqEventBusFactory.cs
  src/SecTester.Bus/Extensions/ServiceCollectionExtensions.cs
  src/SecTester.Bus/SecTester.Bus.csproj
  src/SecTester.Core/Bus/EventBus.cs
  src/SecTester.Repeater/Bus/DefaultRepeaterEventBusFactory.cs
  src/SecTester.Repeater/Bus/EventBusFactory.cs
  src/SecTester.Repeater/Bus/RepeaterEventBusFactory.cs
  src/SecTester.Repeater/DefaultRepeaterFactory.cs
  src/SecTester.Repeater/Repeater.cs
  test/SecTester.Repeater.Tests/Bus/DefaultRepeaterEventBusFactoryTests.cs
  test/SecTester.Repeater.Tests/DefaultRepeaterFactoryTests.cs
  test/SecTester.Repeater.Tests/SecTester.Repeater.Tests.csproj
Labels: Type: enhancement

#84 feat(repeater): implement event handler for incoming requests
  src/SecTester.Repeater/Bus/RequestExecutingEvent.cs
  src/SecTester.Repeater/Bus/RequestExecutingEventHandler.cs
  src/SecTester.Repeater/Bus/RequestExecutingResult.cs
  src/SecTester.Repeater/Extensions/ServiceCollectionExtensions.cs
  src/SecTester.Repeater/README.md
  src/SecTester.Repeater/Repeater.cs
  src/SecTester.Repeater/Runners/Request.cs
  src/SecTester.Repeater/Runners/RequestRunner.cs
  src/SecTester.Repeater/Runners/Response.cs
  test/SecTester.Repeater.Tests/Bus/RequestExecutingEventHandlerTests.cs
Labels: Type: enhancement

#59 feat(scan): define the scan state and issues list retrieval API
  src/SecTester.Scan/Models/Identifiable.cs
  src/SecTester.Scan/Scan.cs
  src/SecTester.Scan/ScanOptions.cs
  test/SecTester.Repeater.Tests/Usings.cs
  test/SecTester.Scan.Tests/Commands/CreateScanTests.cs
  test/SecTester.Scan.Tests/Commands/UploadHarTests.cs
  test/SecTester.Scan.Tests/DefaultScansTests.cs
  test/SecTester.Scan.Tests/Extensions/HttpContentExtensions.cs
  test/SecTester.Scan.Tests/Fixtures/ScanFixture.cs
  test/SecTester.Scan.Tests/Mocks/MockLogger.cs
  test/SecTester.Scan.Tests/ScanTests.cs
  test/SecTester.Scan.Tests/SecTester.Scan.Tests.csproj
  test/SecTester.Scan.Tests/Usings.cs
  test/SecTester.Scan.Tests/packages.lock.json
Labels: Type: enhancement

#87 feat(repeater): implement HTTP request runner
  src/SecTester.Repeater/Extensions/EnumerableExtensions.cs
  src/SecTester.Repeater/Extensions/ListExtensions.cs
  src/SecTester.Repeater/Extensions/ServiceCollectionExtensions.cs
  src/SecTester.Repeater/Runners/HttpRequestRunner.cs
  src/SecTester.Repeater/Runners/RequestRunnerOptions.cs
  src/SecTester.Repeater/Runners/TruncatedBody.cs
  src/SecTester.Repeater/SecTester.Repeater.csproj
  test/SecTester.Repeater.Tests/DefaultRepeaterFactoryTests.cs
  test/SecTester.Repeater.Tests/Extensions/EnumerableExtensionsTests.cs
  test/SecTester.Repeater.Tests/Extensions/ListExtensionsTests.cs
  test/SecTester.Repeater.Tests/Extensions/ServiceCollectionExtensionsTests.cs
  test/SecTester.Repeater.Tests/RepeaterOptionsTests.cs
  test/SecTester.Repeater.Tests/Runners/HttpRequestRunnerTests.cs
  test/SecTester.Repeater.Tests/SecTester.Repeater.Tests.csproj
  test/SecTester.Repeater.Tests/Usings.cs
  test/SecTester.Repeater.Tests/packages.lock.json
Labels: Type: enhancement

#86 feat(scan): add expect method to wait using a custom predicate
  src/SecTester.Scan/Scan.cs
  test/SecTester.Scan.Tests/ScanTests.cs
Labels: Type: enhancement

#92 build(dev-deps): bump semantic-release from 19.0.3 to 19.0.5
  .releaserc
  package-lock.json
  package.json
Labels: Type: dependencies

#93 docs(readme): add notice about supporting both WS and HTTP runners
  src/SecTester.Repeater/README.md
Labels: Type: documentation

#76 feat(scan): provide a default scan factory
  src/SecTester.Core/Utils/StringUtils.cs
  src/SecTester.Scan/CI/DefaultCiDiscovery.cs
  src/SecTester.Scan/Commands/CreateScan.cs
  src/SecTester.Scan/Commands/UploadHar.cs
  src/SecTester.Scan/DefaultScanFactory.cs
  src/SecTester.Scan/DefaultScans.cs
  src/SecTester.Scan/Models/HarSpec/Cache.cs
  src/SecTester.Scan/Models/HarSpec/Content.cs
  src/SecTester.Scan/Models/HarSpec/Cookie.cs
  src/SecTester.Scan/Models/HarSpec/Entry.cs
  src/SecTester.Scan/Models/HarSpec/EntryMessage.cs
  src/SecTester.Scan/Models/HarSpec/Har.cs
  src/SecTester.Scan/Models/HarSpec/Header.cs
  src/SecTester.Scan/Models/HarSpec/Log.cs
  src/SecTester.Scan/Models/HarSpec/Parameter.cs
  src/SecTester.Scan/Models/HarSpec/PostData.cs
  src/SecTester.Scan/Models/HarSpec/PostDataParameter.cs
  src/SecTester.Scan/Models/HarSpec/QueryParameter.cs
  src/SecTester.Scan/Models/HarSpec/RequestMessage.cs
  src/SecTester.Scan/Models/HarSpec/ResponseMessage.cs
  src/SecTester.Scan/Models/HarSpec/Timings.cs
  src/SecTester.Scan/Models/HarSpec/Tool.cs
  src/SecTester.Scan/Models/Identifiable.cs
  src/SecTester.Scan/Models/ScanConfig.cs
  src/SecTester.Scan/Models/Target.cs
  src/SecTester.Scan/Models/TargetOptions.cs
  src/SecTester.Scan/Models/UploadHarOptions.cs
  src/SecTester.Scan/README.md
  src/SecTester.Scan/Scan.cs
  src/SecTester.Scan/ScanFactory.cs
  src/SecTester.Scan/ScanOptions.cs
  src/SecTester.Scan/ScanSettings.cs
  src/SecTester.Scan/ScanSettingsOptions.cs
  src/SecTester.Scan/SecTester.Scan.csproj
  src/SecTester.Scan/Target/Har/Har.cs
  test/Directory.Build.props
  test/SecTester.Core.Tests/Utils/StringUtilsTests.cs
  test/SecTester.Scan.Tests/Commands/CreateScanTests.cs
  test/SecTester.Scan.Tests/Commands/UploadHarTests.cs
  test/SecTester.Scan.Tests/DefaultScanFactoryTests.cs
  test/SecTester.Scan.Tests/DefaultScansTests.cs
  test/SecTester.Scan.Tests/Extensions/ServiceCollectionExtensionsTests.cs
  test/SecTester.Scan.Tests/Fixtures/TestScanSettingsOptions.cs
  test/SecTester.Scan.Tests/Fixtures/TestTargetOptions.cs
  test/SecTester.Scan.Tests/Models/IssueTests.cs
  test/SecTester.Scan.Tests/Models/TargetTests.cs
  test/SecTester.Scan.Tests/Models/UploadHarOptionsTests.cs
  test/SecTester.Scan.Tests/ScanSettingsTests.cs
  test/SecTester.Scan.Tests/ScanTests.cs
  test/SecTester.Scan.Tests/SecTester.Scan.Tests.csproj
  test/SecTester.Scan.Tests/Usings.cs
Labels: Type: enhancement

#90 feat(scan): add expect method to wait for certain issue by severity threshold
  src/SecTester.Scan/Models/Severity.cs
  src/SecTester.Scan/Scan.cs
  test/SecTester.Scan.Tests/ScanTests.cs
Labels: Type: enhancement

#103 fix(scan): register `ScanFactory` in IoC container
  src/SecTester.Scan/DefaultScanFactory.cs
  src/SecTester.Scan/Extensions/ServiceCollectionExtensions.cs
  test/SecTester.Scan.Tests/DefaultScanFactoryTests.cs
  test/SecTester.Scan.Tests/Extensions/ServiceCollectionExtensionsTests.cs
Labels: Type: bug

#102 fix(scan): raise exception when scan enters into failed-status or by timeout
  src/SecTester.Core/Exceptions/SecTesterException.cs
  src/SecTester.Scan/Exceptions/ScanAborted.cs
  src/SecTester.Scan/Exceptions/ScanException.cs
  src/SecTester.Scan/Exceptions/ScanExceptionCode.cs
  src/SecTester.Scan/Exceptions/ScanTimedOut.cs
  src/SecTester.Scan/Scan.cs
  src/SecTester.Scan/ScanOptions.cs
  src/SecTester.Scan/SecTester.Scan.csproj
  src/SecTester.Scan/packages.lock.json
  test/SecTester.Bus.Tests/packages.lock.json
  test/SecTester.Scan.Tests/ScanTests.cs
  test/SecTester.Scan.Tests/Usings.cs
  test/SecTester.Scan.Tests/packages.lock.json
Labels: Type: bug

#105 feat(reporter): define abstractions for formatting assertions
  SecTester.sln
  src/SecTester.Reporter/Formatter.cs
  src/SecTester.Reporter/README.md
  src/SecTester.Reporter/SecTester.Reporter.csproj
  src/SecTester.Reporter/packages.lock.json
  test/SecTester.Reporter.Tests/FormatterTests.cs
  test/SecTester.Reporter.Tests/SecTester.Reporter.Tests.csproj
  test/SecTester.Reporter.Tests/Usings.cs
  test/SecTester.Reporter.Tests/packages.lock.json
Labels: Type: enhancement

#106 feat(runner): provide a base test builder
  SecTester.sln
  src/SecTester.Runner/IssueFound.cs
  src/SecTester.Runner/README.md
  src/SecTester.Runner/SecScan.cs
  src/SecTester.Runner/SecTester.Runner.csproj
  src/SecTester.Runner/packages.lock.json
  test/SecTester.Runner.Tests/SecScanTests.cs
  test/SecTester.Runner.Tests/SecTester.Runner.Tests.csproj
  test/SecTester.Runner.Tests/Usings.cs
  test/SecTester.Runner.Tests/packages.lock.json
Labels: Type: enhancement

#110 refactor(repeater): extract an interface from Repeater
  src/SecTester.Repeater/DefaultRepeaterFactory.cs
  src/SecTester.Repeater/IRepeater.cs
  src/SecTester.Repeater/Repeater.cs
  src/SecTester.Repeater/RepeaterFactory.cs
Labels: Type: refactoring

#94 refactor(scan): implement CI discovery provider
  src/SecTester.Scan/CI/CiDiscovery.cs
  src/SecTester.Scan/CI/CiServer.cs
  src/SecTester.Scan/CI/DefaultCiDiscovery.cs
  src/SecTester.Scan/CI/ResourceUtils.cs
  src/SecTester.Scan/CI/Vendor.cs
  src/SecTester.Scan/CI/VendorMatcher.cs
  src/SecTester.Scan/CI/vendors.json
  src/SecTester.Scan/DefaultScans.cs
  src/SecTester.Scan/SecTester.Scan.csproj
  test/SecTester.Scan.Tests/CI/CiServerTests.cs
  test/SecTester.Scan.Tests/CI/DefaultCiDiscoveryTests.cs
  test/SecTester.Scan.Tests/CI/ResourceUtilsTests.cs
  test/SecTester.Scan.Tests/CI/VendorMatcherTests.cs
  test/SecTester.Scan.Tests/Usings.cs
Labels: Type: refactoring

#114 fix(scan): rename fields according to HAR spec
  src/SecTester.Scan/Models/HarSpec/Entry.cs
  src/SecTester.Scan/Models/HarSpec/ResponseMessage.cs
Labels: Type: bug

#116 fix(repeater): specify a default ping interval to 10s
  src/SecTester.Repeater/Repeater.cs
  test/SecTester.Repeater.Tests/RepeaterTests.cs
Labels: Type: bug

#120 refactor(*): prevent possible memory leaks
  src/SecTester.Bus/Dispatchers/HttpCommandDispatcher.cs
  src/SecTester.Bus/Dispatchers/RateLimitedHandler.cs
  src/SecTester.Bus/Dispatchers/RmqEventBus.cs
  src/SecTester.Repeater/Runners/HttpRequestRunner.cs
Labels: Type: refactoring

#122 fix(scan): expect at least one issue given severity
  src/SecTester.Scan/Scan.cs
Labels: Type: bug

#124 fix(bus): convert single element sequence in headers to string
  src/SecTester.Bus/Dispatchers/MessageSerializer.cs
  src/SecTester.Bus/Internal/HeadersConverter.cs
  test/SecTester.Bus.Tests/Dispatchers/MessageSerializerTests.cs
  test/SecTester.Bus.Tests/Fixtures/FooBaz.cs
Labels: Type: bug

#126 fix(bus): use the same channel for consuming and publishing in RPC
  src/SecTester.Bus/Dispatchers/PendingMessage.cs
  src/SecTester.Bus/Dispatchers/RmqEventBus.cs
  test/SecTester.Bus.Tests/Dispatchers/RmqEventBusTests.cs
Labels: Type: bug

#128 fix(bus): unexpected return type when using reflection to invoke a method
  src/SecTester.Bus/Dispatchers/RmqEventBus.cs
  src/SecTester.Bus/Extensions/TaskExtensions.cs
  test/SecTester.Bus.Tests/Extensions/TaskExtensionsTests.cs
Labels: Type: bug

#112 feat(reporter): implement plain text issue formatter
  .gitattributes
  src/SecTester.Reporter/DefaultFormatter.cs
  src/SecTester.Reporter/SecTester.Reporter.csproj
  src/SecTester.Runner/SecRunner.cs
  test/SecTester.Reporter.Tests/DefaultFormatterTests.cs
  test/SecTester.Reporter.Tests/FormatterTests.cs
  test/SecTester.Reporter.Tests/Usings.cs
Labels: Type: enhancement

#134 fix(bus): configure rate limiter in accordance with actual settings
  src/SecTester.Bus/Commands/HttpRequest.cs
  src/SecTester.Bus/Dispatchers/RateLimitedHandler.cs
  src/SecTester.Bus/Exceptions/HttpStatusException.cs
  src/SecTester.Bus/Extensions/ServiceCollectionExtensions.cs
  src/SecTester.Bus/RetryStrategies/ExponentialBackoffRetryStrategy.cs
  src/SecTester.Core/Bus/Command.cs
  test/SecTester.Bus.Tests/Dispatchers/DefaultRmqConnectionManagerTests.cs
  test/SecTester.Bus.Tests/Dispatchers/HttpCommandDispatcherTests.cs
  test/SecTester.Bus.Tests/Dispatchers/RmqEventBusTests.cs
  test/SecTester.Bus.Tests/Fixtures/ConcreteCommand.cs
  test/SecTester.Bus.Tests/Fixtures/ConcreteCommand2.cs
  test/SecTester.Bus.Tests/RetryStrategies/ExponentialBackoffRetryStrategyTests.cs
  test/SecTester.Bus.Tests/Usings.cs
  test/SecTester.Core.Tests/Bus/CommandTests.cs
  test/SecTester.Core.Tests/Fixtures/TestCommandWithTtl.cs
Labels: Type: bug

#132 fix(core): enable ansi colors console mode on windows
  src/SecTester.Core/Extensions/ServiceCollectionExtensions.cs
  src/SecTester.Core/Logger/AnsiCodeColor.cs
  src/SecTester.Core/Logger/AnsiCodeColorizer.cs
  src/SecTester.Core/Logger/ColoredConsoleFormatter.cs
  src/SecTester.Core/Logger/DefaultAnsiCodeColorizer.cs
  src/SecTester.Core/Utils/ConsoleUtils.cs
  src/SecTester.Repeater/DefaultRepeaterFactory.cs
  src/SecTester.Repeater/Repeater.cs
  test/SecTester.Core.Tests/Logger/AnsiCodeColorTests.cs
  test/SecTester.Core.Tests/Logger/ColoredConsoleFormatterTests.cs
  test/SecTester.Core.Tests/Logger/DefaultAnsiCodeColorizerTests.cs
  test/SecTester.Repeater.Tests/DefaultRepeaterFactoryTests.cs
  test/SecTester.Repeater.Tests/RepeaterTests.cs
  test/SecTester.Repeater.Tests/Usings.cs
Labels: Type: bug

#138 fix(core): provide product version from assembly metadata
  src/SecTester.Core/Configuration.cs
  test/SecTester.Core.Tests/ConfigurationTests.cs
Labels: Type: bug

#141 docs(readme): add link to the demo project
  README.md
Labels: Type: documentation

#142 docs(readme): supersede legacy domain
  README.md
  src/SecTester.Bus/README.md
  src/SecTester.Core/README.md
  src/SecTester.Repeater/README.md
  src/SecTester.Reporter/README.md
  src/SecTester.Runner/README.md
  test/SecTester.Bus.Tests/Extensions/ServiceCollectionExtensionsTests.cs
  test/SecTester.Core.Tests/ConfigurationTests.cs
  test/SecTester.Core.Tests/Extensions/ServiceCollectionExtensionsTests.cs
  test/SecTester.Repeater.Tests/Bus/DefaultRepeaterEventBusFactoryTests.cs
  test/SecTester.Repeater.Tests/DefaultRepeaterFactoryTests.cs
  test/SecTester.Reporter.Tests/DefaultFormatterTests.cs
  test/SecTester.Runner.Tests/SecRunnerTests.cs
  test/SecTester.Scan.Tests/DefaultScanFactoryTests.cs
  test/SecTester.Scan.Tests/DefaultScansTests.cs
  test/SecTester.Scan.Tests/Extensions/ServiceCollectionExtensionsTests.cs
Labels: Type: documentation

#140 fix(runner): load credentials before creating a composite root
  src/SecTester.Runner/README.md
  src/SecTester.Runner/SecRunner.cs
  test/SecTester.Runner.Tests/SecRunnerTests.cs
Labels: Type: bug

#144 fix(scan): utilize m and ms units for `TargetTimeout` and `SlowEpTimeout` accordingly
  src/SecTester.Scan/DefaultScanFactory.cs
  src/SecTester.Scan/ScanSettings.cs
  src/SecTester.Scan/ScanSettingsBuilder.cs
  test/SecTester.Scan.Tests/ScanSettingsBuilderTests.cs
  test/SecTester.Scan.Tests/ScanSettingsTests.cs
Labels: Type: bug

#147 fix(repeater): refuse an empty response to `CreateRepeaterRequest`
  src/SecTester.Repeater/Api/CreateRepeaterRequest.cs
Labels: Type: bug
