Repository NeuraLegion/sectester-net, pull requests merged in 2022-11, with the labels that each got.

#8 ci: collect coverage
  .github/workflows/coverage.yml
Labels: Type: tooling

#7 feat(core): provide the ability to set a credentials
  src/SecTester.Core/Configuration.cs
  src/SecTester.Core/Credentials.cs
  test/SecTester.Core.Tests/CredentialsTests.cs
Labels: Type: enhancement

#16 docs(readme): clarify installation instructions
  README.md
Labels: Type: documentation

#17 build: enable locked mode
  .github/workflows/auto-build.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  CONTRIBUTING.md
Labels: Type: tooling

#13 feat(core): provide an abstraction to manage `CredentialProvider`
  src/SecTester.Core/Configuration.cs
  src/SecTester.Core/CredentialProvider.cs
  src/SecTester.Core/Utils/TaskUtils.cs
  test/SecTester.Core.Tests/ConfigurationTests.cs
  test/SecTester.Core.Tests/Usings.cs
  test/SecTester.Core.Tests/Utils/TaskUtilsTests.cs
Labels: Type: enhancement

#14 feat(core): implement `EnvCredentialProvider` to obtain credentials from env variables
  src/SecTester.Core/Configuration.cs
  src/SecTester.Core/CredentialProviders/EnvCredentialProvider.cs
  src/SecTester.Core/README.md
  src/SecTester.Core/SecTester.Core.csproj
  test/SecTester.Core.Tests/ConfigurationTests.cs
  test/SecTester.Core.Tests/CredentialProviders/EnvCredentialProviderTests.cs
  test/SecTester.Core.Tests/SecTester.Core.Tests.csproj
Labels: Type: enhancement

#19 feat(core): allow creating custom messages with a predefined set of fields
  src/SecTester.Core/Bus/Command.cs
  src/SecTester.Core/Bus/Event.cs
  src/SecTester.Core/Bus/Message.cs
  src/SecTester.Core/SecTester.Core.csproj
  test/SecTester.Core.Tests/Bus/CommandTests.cs
  test/SecTester.Core.Tests/Bus/MessageTests.cs
  test/SecTester.Core.Tests/SecTester.Core.Tests.csproj
  test/SecTester.Core.Tests/Usings.cs
Labels: Type: enhancement

#21 feat(core): allow creating custom dispatchers for both `Command` and `Event`
  src/SecTester.Core/Bus/Command.cs
  src/SecTester.Core/Bus/CommandDispatcher.cs
  src/SecTester.Core/Bus/Event.cs
  src/SecTester.Core/Bus/EventDispatcher.cs
  src/SecTester.Core/Bus/Message.cs
  test/SecTester.Core.Tests/Bus/CommandTests.cs
  test/SecTester.Core.Tests/Bus/EventTests.cs
  test/SecTester.Core.Tests/Usings.cs
Labels: Type: enhancement

#29 feat(core): define an abstraction for `EventBus`
  src/SecTester.Core/Bus/Command.cs
  src/SecTester.Core/Bus/CommandDispatcher.cs
  src/SecTester.Core/Bus/Event.cs
  src/SecTester.Core/Bus/EventBus.cs
  src/SecTester.Core/Bus/EventDispatcher.cs
  src/SecTester.Core/Bus/EventHandler.cs
  src/SecTester.Core/Bus/Message.cs
  src/SecTester.Core/Internal/IsExternalInit.cs
  src/SecTester.Core/README.md
  src/SecTester.Core/SecTester.Core.csproj
  src/SecTester.Core/Unit.cs
  test/SecTester.Core.Tests/Bus/CommandTests.cs
  test/SecTester.Core.Tests/Bus/EventTests.cs
  test/SecTester.Core.Tests/Bus/MessageTests.cs
  test/SecTester.Core.Tests/UnitTests.cs
Labels: Type: enhancement

#31 style: clarify naming convention rules
  .editorconfig
  src/SecTester.Core/Unit.cs
  test/SecTester.Core.Tests/UnitTests.cs
Labels: Type: cleanup

#32 test(core): ensure tests results are determined
  test/SecTester.Core.Tests/Utils/TaskUtilsTests.cs
Labels: Type: tests

#30 feat(core): introduce a retry strategy
  src/SecTester.Core/Bus/RetryStrategy.cs
Labels: Type: enhancement

#35 refactor(core): remove redundant command constructors
  src/SecTester.Core/Bus/Command.cs
Labels: Type: refactoring

#36 test(core): clean up tests
  test/SecTester.Core.Tests/Bus/CommandTests.cs
  test/SecTester.Core.Tests/Bus/EventTests.cs
  test/SecTester.Core.Tests/Extensions/ServiceCollectionExtensionsTests.cs
Labels: Type: tests

#37 refactor(core): get rid of dynamic dispatch
  src/SecTester.Core/Bus/CommandDispatcher.cs
Labels: Type: refactoring

#34 feat(bus): implement HTTP command dispatcher
  SecTester.sln
  src/SecTester.Bus/Commands/HttpRequest.cs
  src/SecTester.Bus/Dispatchers/HttpCommandDispatcher.cs
  src/SecTester.Bus/Dispatchers/HttpCommandDispatcherConfig.cs
  src/SecTester.Bus/Dispatchers/RateLimitedHandler.cs
  src/SecTester.Bus/Extensions/ServiceCollectionExtensions.cs
  src/SecTester.Bus/Internal/IsExternalInit.cs
  src/SecTester.Bus/README.md
  src/SecTester.Bus/SecTester.Bus.csproj
  src/SecTester.Bus/packages.lock.json
  test/SecTester.Bus.Tests/Dispatchers/HttpCommandDispatcherTests.cs
  test/SecTester.Bus.Tests/Extensions/ServiceCollectionExtensionsTests.cs
  test/SecTester.Bus.Tests/SecTester.Bus.Tests.csproj
  test/SecTester.Bus.Tests/Usings.cs
  test/SecTester.Bus.Tests/packages.lock.json
Labels: Type: enhancement

#39 refactor(core): clarify generic types
  src/SecTester.Core/Bus/EventBus.cs
  src/SecTester.Core/Bus/EventDispatcher.cs
  src/SecTester.Core/Bus/EventHandler.cs
  src/SecTester.Core/Bus/EventListener.cs
Labels: Type: refactoring

#33 feat(core): implement a custom logging provider
  src/SecTester.Bus/packages.lock.json
  src/SecTester.Core/Configuration.cs
  src/SecTester.Core/Extensions/ServiceCollectionExtensions.cs
  src/SecTester.Core/Logger/ColoredConsoleFormatter.cs
  src/SecTester.Core/Logger/DefaultConsoleFormatter.cs
  src/SecTester.Core/SecTester.Core.csproj
  src/SecTester.Core/Utils/LocalSystemTimeProvider.cs
  src/SecTester.Core/Utils/SystemTimeProvider.cs
  src/SecTester.Core/Utils/UtcSystemTimeProvider.cs
  src/SecTester.Core/packages.lock.json
  test/SecTester.Bus.Tests/packages.lock.json
  test/SecTester.Core.Tests/ConfigurationTests.cs
  test/SecTester.Core.Tests/Extensions/ServiceCollectionExtensionsTests.cs
  test/SecTester.Core.Tests/Logger/ColoredConsoleFormatterTests.cs
  test/SecTester.Core.Tests/Logger/DefaultConsoleFormatterTests.cs
  test/SecTester.Core.Tests/Utils/LocalSystemTimeProviderTests.cs
  test/SecTester.Core.Tests/Utils/UtcSystemTimeProviderTests.cs
  test/SecTester.Core.Tests/packages.lock.json
Labels: Priority: low, Type: enhancement

#41 feat(core): implement an attribute to set custom event name
  src/SecTester.Core/Bus/EventNameAttribute.cs
  test/SecTester.Core.Tests/Bus/EventNameAttributeTests.cs
Labels: Type: enhancement

#46 refactor(core): extract helps methods to util class
  src/SecTester.Core/Bus/Message.cs
  src/SecTester.Core/Bus/MessageTypeAttribute.cs
  src/SecTester.Core/Utils/MessageUtils.cs
  test/SecTester.Core.Tests/Bus/CommandTests.cs
  test/SecTester.Core.Tests/Bus/EventNameAttributeTests.cs
  test/SecTester.Core.Tests/Bus/EventTests.cs
  test/SecTester.Core.Tests/Bus/MessageTests.cs
  test/SecTester.Core.Tests/Bus/MessageTypeAttributeTests.cs
  test/SecTester.Core.Tests/ConfigurationTests.cs
  test/SecTester.Core.Tests/CredentialProviders/EnvCredentialProviderTests.cs
  test/SecTester.Core.Tests/Extensions/ServiceCollectionExtensionsTests.cs
  test/SecTester.Core.Tests/Logger/ColoredConsoleFormatterTests.cs
  test/SecTester.Core.Tests/Logger/DefaultConsoleFormatterTests.cs
  test/SecTester.Core.Tests/Usings.cs
  test/SecTester.Core.Tests/Utils/LocalSystemTimeProviderTests.cs
  test/SecTester.Core.Tests/Utils/MessageUtilsTests.cs
  test/SecTester.Core.Tests/Utils/TaskUtilsTests.cs
  test/SecTester.Core.Tests/Utils/UtcSystemTimeProviderTests.cs
Labels: Type: refactoring

#38 feat(bus): implement Pub/Sub pattern for RabbitMQ
  .editorconfig
  src/SecTester.Bus/Dispatchers/ConsumedMessage.cs
  src/SecTester.Bus/Dispatchers/DefaultMessageSerializer.cs
  src/SecTester.Bus/Dispatchers/DefaultRmqConnectionManager.cs
  src/SecTester.Bus/Dispatchers/HttpCommandDispatcher.cs
  src/SecTester.Bus/Dispatchers/HttpCommandDispatcherConfig.cs
  src/SecTester.Bus/Dispatchers/MessageSerializer.cs
  src/SecTester.Bus/Dispatchers/PendingMessage.cs
  src/SecTester.Bus/Dispatchers/RmqConnectionManager.cs
  src/SecTester.Bus/Dispatchers/RmqEventBus.cs
  src/SecTester.Bus/Dispatchers/RmqEventBusOptions.cs
  src/SecTester.Bus/Exceptions/EventHandlerNotFoundException.cs
  src/SecTester.Bus/Exceptions/NoSubscriptionFoundException.cs
  src/SecTester.Bus/Extensions/GenericTypeExtensions.cs
  src/SecTester.Bus/Extensions/ServiceCollectionExtensions.cs
  src/SecTester.Bus/Extensions/TaskExtensions.cs
  src/SecTester.Bus/SecTester.Bus.csproj
  src/SecTester.Bus/packages.lock.json
  test/Directory.Build.props
  test/SecTester.Bus.Tests/Dispatchers/DefaultMessageSerializerTests.cs
  test/SecTester.Bus.Tests/Dispatchers/DefaultRmqConnectionManagerTests.cs
  test/SecTester.Bus.Tests/Dispatchers/HttpCommandDispatcherTests.cs
  test/SecTester.Bus.Tests/Dispatchers/RmqEventBusOptionsTests.cs
  test/SecTester.Bus.Tests/Dispatchers/RmqEventBusTests.cs
  test/SecTester.Bus.Tests/Exceptions/EventHandlerNotFoundExceptionTests.cs
  test/SecTester.Bus.Tests/Exceptions/NoSubscriptionFoundException.cs
  test/SecTester.Bus.Tests/Extensions/GenericTypeExtensionsTests.cs
  test/SecTester.Bus.Tests/Extensions/ServiceCollectionExtensionsTests.cs
  test/SecTester.Bus.Tests/Extensions/TaskExtensionsTests.cs
  test/SecTester.Bus.Tests/Fixtures/BazQux.cs
  test/SecTester.Bus.Tests/Fixtures/ConcreteEvent.cs
  test/SecTester.Bus.Tests/Fixtures/ConcreteEvent2.cs
  test/SecTester.Bus.Tests/Fixtures/ConcreteEvent3.cs
  test/SecTester.Bus.Tests/Fixtures/ConcreteFirstHandler.cs
  test/SecTester.Bus.Tests/Fixtures/ConcreteSecondHandler.cs
  test/SecTester.Bus.Tests/Fixtures/ConcreteThirdHandler.cs
  test/SecTester.Bus.Tests/Fixtures/FooBar.cs
  test/SecTester.Bus.Tests/SecTester.Bus.Tests.csproj
  test/SecTester.Bus.Tests/Usings.cs
  test/SecTester.Bus.Tests/packages.lock.json
  test/SecTester.Core.Tests/Bus/CommandTests.cs
  test/SecTester.Core.Tests/Bus/EventTests.cs
  test/SecTester.Core.Tests/Bus/MessageTests.cs
  test/SecTester.Core.Tests/Bus/MessageTypeAttributeTests.cs
  test/SecTester.Core.Tests/CredentialProviders/EnvCredentialProviderTests.cs
  test/SecTester.Core.Tests/Fixtures/TestCommand.cs
  test/SecTester.Core.Tests/Fixtures/TestCommandWithTtl.cs
  test/SecTester.Core.Tests/Fixtures/TestEvent.cs
  test/SecTester.Core.Tests/Fixtures/TestEvent2.cs
  test/SecTester.Core.Tests/Fixtures/TestMessage.cs
  test/SecTester.Core.Tests/SecTester.Core.Tests.csproj
  test/SecTester.Core.Tests/Utils/MessageUtilsTests.cs
Labels: Type: enhancement

#48 feat(bus): implement RPC pattern for RabbitMQ
  .editorconfig
  src/SecTester.Bus/Dispatchers/RmqEventBus.cs
  test/SecTester.Bus.Tests/Dispatchers/RmqEventBusTests.cs
  test/SecTester.Bus.Tests/Fixtures/ConcreteCommand.cs
  test/SecTester.Bus.Tests/Fixtures/ConcreteCommand2.cs
Labels: Type: enhancement

#52 feat(bus): rework `HttpRequest` to accept `HttpContent` and generic query strings
  src/SecTester.Bus/Commands/HttpRequest.cs
  src/SecTester.Bus/Dispatchers/HttpCommandDispatcher.cs
  src/SecTester.Bus/README.md
  test/SecTester.Bus.Tests/Dispatchers/HttpCommandDispatcherTests.cs
  test/SecTester.Bus.Tests/Usings.cs
Labels: Type: enhancement

#53 refactor(bus): handle transient exceptions suing a retry strategy
  src/SecTester.Bus/Dispatchers/DefaultRmqConnectionManager.cs
  src/SecTester.Bus/Dispatchers/HttpCommandDispatcher.cs
  src/SecTester.Bus/Dispatchers/RmqEventBus.cs
  src/SecTester.Bus/Extensions/ServiceCollectionExtensions.cs
  src/SecTester.Bus/RetryStrategies/ExponentialBackoffOptions.cs
  src/SecTester.Bus/RetryStrategies/ExponentialBackoffRetryStrategy.cs
  src/SecTester.Bus/SecTester.Bus.csproj
  src/SecTester.Core/Bus/RetryStrategy.cs
  test/SecTester.Bus.Tests/Dispatchers/DefaultRmqConnectionManagerTests.cs
  test/SecTester.Bus.Tests/Dispatchers/HttpCommandDispatcherTests.cs
  test/SecTester.Bus.Tests/Dispatchers/RmqEventBusTests.cs
  test/SecTester.Bus.Tests/Fixtures/MockInterface.cs
  test/SecTester.Bus.Tests/RetryStrategies/ExponentialBackoffRetryStrategyTests.cs
  test/SecTester.Bus.Tests/SecTester.Bus.Tests.csproj
Labels: Type: refactoring

#54 docs(bus): describe a guide on how to use the event bus
  src/SecTester.Bus/README.md
Labels: Type: documentation

#62 refactor(core): extract util methods to work with URL to a helper class
  src/SecTester.Core/Logger/ColoredConsoleFormatter.cs
  src/SecTester.Core/Logger/DefaultConsoleFormatter.cs
  src/SecTester.Core/Utils/LocalSystemTimeProvider.cs
  src/SecTester.Core/Utils/SystemTimeProvider.cs
  src/SecTester.Core/Utils/UrlUtils.cs
  src/SecTester.Core/Utils/UtcSystemTimeProvider.cs
  src/SecTester.Core/packages.lock.json
  test/SecTester.Core.Tests/Logger/ColoredConsoleFormatterTests.cs
  test/SecTester.Core.Tests/Logger/DefaultConsoleFormatterTests.cs
  test/SecTester.Core.Tests/Utils/StringUtilsTests.cs
  test/SecTester.Core.Tests/Utils/UrlUtilsTests.cs
  test/SecTester.Core.Tests/packages.lock.json
Labels: Type: refactoring

#65 refactor(bus): convert `MessageSerializer` to the static class
  src/SecTester.Bus/Dispatchers/DefaultMessageSerializer.cs
  src/SecTester.Bus/Dispatchers/HttpCommandDispatcher.cs
  src/SecTester.Bus/Dispatchers/MessageSerializer.cs
  src/SecTester.Bus/Dispatchers/RmqEventBus.cs
  src/SecTester.Bus/Extensions/ServiceCollectionExtensions.cs
  test/SecTester.Bus.Tests/Dispatchers/HttpCommandDispatcherTests.cs
  test/SecTester.Bus.Tests/Dispatchers/MessageSerializerTests.cs
  test/SecTester.Bus.Tests/Dispatchers/RmqEventBusTests.cs
Labels: Type: refactoring

#66 chore: update NuGet authors
  src/Directory.Build.props
Labels: Type: tooling

#57 feat(scan): implement a single entry HAR builder
  src/SecTester.Scan/Internal/IsExternalInit.cs
  src/SecTester.Scan/Models/AttackParamLocation.cs
  src/SecTester.Scan/Models/Comment.cs
  src/SecTester.Scan/Models/Discovery.cs
  src/SecTester.Scan/Models/Frame.cs
  src/SecTester.Scan/Models/Issue.cs
  src/SecTester.Scan/Models/IssueGroup.cs
  src/SecTester.Scan/Models/Module.cs
  src/SecTester.Scan/Models/Protocol.cs
  src/SecTester.Scan/Models/Response.cs
  src/SecTester.Scan/Models/ScanConfig.cs
  src/SecTester.Scan/Models/ScanState.cs
  src/SecTester.Scan/Models/ScanStatus.cs
  src/SecTester.Scan/Models/Screenshot.cs
  src/SecTester.Scan/Models/Severity.cs
  src/SecTester.Scan/Models/TestType.cs
  src/SecTester.Scan/Models/WebsocketFrame.cs
  src/SecTester.Scan/Scan.cs
  src/SecTester.Scan/ScanFactory.cs
  src/SecTester.Scan/ScanOptions.cs
  src/SecTester.Scan/ScanSettingsOptions.cs
  src/SecTester.Scan/Scans.cs
  src/SecTester.Scan/SecTester.Scan.csproj
  src/SecTester.Scan/Target/Har/Cookie.cs
  src/SecTester.Scan/Target/Har/Header.cs
  src/SecTester.Scan/Target/Har/Message.cs
  src/SecTester.Scan/Target/Har/Parameter.cs
  src/SecTester.Scan/Target/Har/PostData.cs
  src/SecTester.Scan/Target/Har/PostDataParameter.cs
  src/SecTester.Scan/Target/Har/QueryParameter.cs
  src/SecTester.Scan/Target/Har/Request.cs
  src/SecTester.Scan/Target/Target.cs
  src/SecTester.Scan/Target/TargetOptions.cs
  test/SecTester.Core.Tests/ConfigurationTests.cs
  test/SecTester.Core.Tests/CredentialsTests.cs
  test/SecTester.Scan.Tests/Models/IssueTests.cs
  test/SecTester.Scan.Tests/Models/UploadHarOptionsTests.cs
  test/SecTester.Scan.Tests/ScanTests.cs
  test/SecTester.Scan.Tests/SecTester.Scan.Tests.csproj
  test/SecTester.Scan.Tests/Target/TargetTests.cs
  test/SecTester.Scan.Tests/Usings.cs
Labels: Type: enhancement

#67 refactor(bus): provide a meaningful error description to the client
  src/SecTester.Bus/Dispatchers/HttpCommandDispatcher.cs
  src/SecTester.Bus/Exceptions/HttpStatusException.cs
  src/SecTester.Bus/Extensions/HttpResponseMessageExtensions.cs
  test/SecTester.Bus.Tests/Extensions/HttpResponseMessageExtensionsTests.cs
Labels: Type: refactoring

#58 feat(scan): introduce a client to manage scans via REST API
  src/.editorconfig
  src/SecTester.Bus/SecTester.Bus.csproj
  src/SecTester.Core/Exceptions/SecTesterException.cs
  src/SecTester.Scan/CI/CiDiscovery.cs
  src/SecTester.Scan/CI/CiServer.cs
  src/SecTester.Scan/CI/DefaultCiDiscovery.cs
  src/SecTester.Scan/Commands/CreateScan.cs
  src/SecTester.Scan/Commands/DeleteScan.cs
  src/SecTester.Scan/Commands/GetScan.cs
  src/SecTester.Scan/Commands/ListIssues.cs
  src/SecTester.Scan/Commands/StopScan.cs
  src/SecTester.Scan/Commands/UploadHar.cs
  src/SecTester.Scan/DefaultScans.cs
  src/SecTester.Scan/Extensions/ServiceCollectionExtensions.cs
  src/SecTester.Scan/Models/Identifiable.cs
  src/SecTester.Scan/SecTester.Scan.csproj
  src/SecTester.Scan/packages.lock.json
  test/SecTester.Bus.Tests/packages.lock.json
  test/SecTester.Scan.Tests/CI/DefaultCiDiscoveryTests.cs
  test/SecTester.Scan.Tests/Commands/CreateScanTests.cs
  test/SecTester.Scan.Tests/Commands/UploadHarTests.cs
  test/SecTester.Scan.Tests/DefaultScansTests.cs
  test/SecTester.Scan.Tests/Extensions/ServiceCollectionExtensionsTests.cs
  test/SecTester.Scan.Tests/Fixtures/ScanFixture.cs
  test/SecTester.Scan.Tests/SecTester.Scan.Tests.csproj
  test/SecTester.Scan.Tests/Target/TargetTests.cs
  test/SecTester.Scan.Tests/Usings.cs
  test/SecTester.Scan.Tests/packages.lock.json
Labels: Type: enhancement

#71 feat(repeater): define base abstractions to manage repeaters
  SecTester.sln
  src/SecTester.Repeater/Bus/EventBusFactory.cs
  src/SecTester.Repeater/Internal/IsExternalInit.cs
  src/SecTester.Repeater/Protocol.cs
  src/SecTester.Repeater/README.md
  src/SecTester.Repeater/Repeater.cs
  src/SecTester.Repeater/RepeaterOptions.cs
  src/SecTester.Repeater/RepeaterStatus.cs
  src/SecTester.Repeater/Repeaters.cs
  src/SecTester.Repeater/Runners/RequestRunnerOptions.cs
  src/SecTester.Repeater/SecTester.Repeater.csproj
  src/SecTester.Repeater/packages.lock.json
  test/SecTester.Repeater.Tests/SecTester.Repeater.Tests.csproj
  test/SecTester.Repeater.Tests/Usings.cs
  test/SecTester.Repeater.Tests/packages.lock.json
Labels: Type: enhancement
